CREATE DATABASE RestaurantDB_V01
GO
USE RestaurantDB_V01
GO

CREATE TABLE RESTUARANT(
	id INT PRIMARY KEY,
	name NVARCHAR(50) NOT NULL,
	city NVARCHAR(20) NOT NULL,
	address NVARCHAR(50) NOT NULL,
	numOfEmp INT,
	phone INT NOT NULL,
	startDate DATE,
);

CREATE TABLE MANAGER(
	id INT PRIMARY KEY,
	name NVARCHAR(50) NOT NULL,
	salary FLOAT NOT NULL,
	gender CHAR(1) NOT NULL,
	address NVARCHAR(50),
	phone INT NOT NULL,
	age INTEGER,
	birthday DATE,
	res_id INT FOREIGN KEY REFERENCES RESTUARANT(id),
);

CREATE TABLE CHEFF(
	id INT PRIMARY KEY,
	name NVARCHAR(20) NOT NULL,
	address NVARCHAR(50),
	age INT,
	salary FLOAT NOT NULL,
	gender CHAR(1) NOT NULL,
	birthday DATE,
	phone INT NOT NULL,
	res_id INT FOREIGN KEY REFERENCES RESTUARANT(id),
);

CREATE TABLE BRANCHES(
	id INT PRIMARY KEY,
	name NVARCHAR(30) NOT NULL,
	address NVARCHAR(50),
	phone INT NOT NULL,
	city NVARCHAR(20),
	numOfEmp INT,
	startDate DATE,
  res_id INT FOREIGN KEY REFERENCES RESTUARANT(id),
);

CREATE TABLE EMPLOYEE(
	id INTEGER PRIMARY KEY ,
	name NVARCHAR(20) NOT NULL,
	gender CHAR(1) NOT NULL,
	age INT,
	phone INT NOT NULL,
	address NVARCHAR(50),
	birthday DATE,
	salary FLOAT NOT NULL,
	branch_id INT FOREIGN KEY REFERENCES BRANCHES(id),
	res_id INT FOREIGN KEY REFERENCES RESTUARANT(id),
);

CREATE TABLE CUSTOMER(
	id INT PRIMARY KEY,
	name NVARCHAR(20) NOT NULL,
	type NVARCHAR(20) NOT NULL,
	phone INT not null,
	address NVARCHAR(50),
	res_id INT FOREIGN KEY REFERENCES RESTUARANT(id),
);

CREATE TABLE ORDER_CUSTOMER(
	id INT PRIMARY KEY,
	orderDate DATE NOT NULL,
	type NVARCHAR(20) NOT NULL,
	total_price FLOAT NOT NULL,
	billNo INT FOREIGN KEY REFERENCES BILL(id),
);

CREATE TABLE MENU(
	id INT PRIMARY KEY,
	foodName NVARCHAR(20) NOT NULL,
	type NVARCHAR(20) NOT NULL,
	price FLOAT NOT NULL,
	branch_id INT FOREIGN KEY REFERENCES BRANCHES(id),
	res_id INT FOREIGN KEY REFERENCES RESTUARANT(id),
);

CREATE TABLE BILL(
	id INT PRIMARY KEY,
	payDate TIME NOT NULL,
	foodName NVARCHAR(30) NOT NULL,
	datetime DATE NOT NULL,
	cus_id INT FOREIGN KEY REFERENCES CUSTOMER(id),
	branch_id INT FOREIGN KEY REFERENCES BRANCHES(id),
	res_id INT FOREIGN KEY REFERENCES RESTUARANT(id),
);

ALTER TABLE CUSTOMER
	ADD ordNo INT;

ALTER TABLE CUSTOMER
	ADD branch_id INT;

ALTER TABLE CUSTOMER
	ADD CONSTRAINT CONSTRAINT_fk1 FOREIGN KEY(ordNo) REFERENCES ORDER_CUSTOMER(id);

ALTER TABLE CUSTOMER
	ADD CONSTRAINT CONSTRAINT_fk2 FOREIGN KEY(branch_id) REFERENCES BRANCHES(id);

ALTER TABLE Bill 
	ADD CONSTRAINT CONSTRAINT_fk2 FOREIGN KEY(c_id) REFERENCES Customer(id);

ALTER TABLE Menu 
	ADD CONSTRAINT CONSTRAINT_fk3 FOREIGN KEY(b_id) REFERENCES Branches(id);
